#მომხარებელს შემოატანინეთ ორი რიცხვი, შემდეგ ამ 2 რიცხვს შორის ჩაატარეთ ყველა არითმეტიკული ოპერატორი (+, -, *, /, **)
number1 =  input("enter your numbrer")
number2 = input('enter number:')
print = str("enter number" * "enter your number" )
print = str("enter number" ** "enter your number" )
print = str("enter number" + "enter your number" )
print = str("enter number" - "enter your number" )
print = str("enter number" // "enter your number" )
print = str("enter number" / "enter your number" )